<?php

/**
 * @file
 * The main Islandora Usage Stats Charts module file.
 */

/**
 * Implements hook_permission().
 */
function islandora_usage_stats_csv_permission() {
  return array(
    'download islandora usage stats data' => array(
      'title' => t('Download object-level usage stats data'),
      'description' => t('Download object-level usage stats data'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_usage_stats_csv_menu() {
  $items['admin/islandora/tools/islandora_usage_stats_csv'] = array(
    'title' => 'Islandora Usage Stats CSV',
    'description' => 'Configure the Islandora Usage Stats CSV module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_usage_stats_csv_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora/object/%islandora_object/usage_stats_csv'] = array(
    'page callback' => 'islandora_usage_stats_csv_download_csv',
    'page arguments' => array(2),
    // Access control is handled in the callback so we can respond with
    // just a 403 and no HTML markup.
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Admin form definition.
 */
function islandora_usage_stats_csv_admin_settings() {
  $form = array();
  $form['islandora_usage_stats_csv_per_ds'] = array(
    '#type' => 'checkbox',
    '#title' => t('Provide datastream-level download statistics'),
    '#default_value' => variable_get('islandora_usage_stats_csv_per_ds', 1),
    '#description' => t("If enabled, each datastream that has been downloaded will have its own row in the CSV file; if not, all downloads usage data will be combined."),
  );
  return system_settings_form($form);
}

/**
 * Menu item callback.
 *
 * Gets usage data and prepare it for download.
 */
function islandora_usage_stats_csv_download_csv($object) {
  if (!islandora_object_access('download islandora usage stats data', $object)) {
    drupal_add_http_header('Status', '403 Forbidden');
    exit();
  }

  module_load_include('inc', 'islandora_usage_stats_csv', 'includes/utilities');
  $per_ds = variable_get('islandora_usage_stats_csv_per_ds', 1);
  $csv_output = islandora_usage_stats_csv_generate_csv($object, $per_ds);

  drupal_add_http_header('Content-type', 'text/csv');
  drupal_add_http_header('Content-length', strlen($csv_output));
  $filename = 'usage_stats.csv';
  drupal_add_http_header('Content-Disposition', 'attachment; filename="' . $filename . '"');
  print $csv_output;
  drupal_page_footer();
}
