<?php

/**
 * @file
 * The main Islandora Usage Stats Charts module file.
 */

// Includes blocks.
require_once dirname(__FILE__) . '/includes/blocks.inc';

/**
 * Implements hook_permission().
 */
function islandora_usage_stats_csv_permission() {
  return array(
    'download islandora usage stats data' => array(
      'title' => t('Download object-level usage stats data'),
      'description' => t('Download object-level usage stats data'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_usage_stats_csv_menu() {
  $items['admin/islandora/tools/islandora_usage_stats_csv'] = array(
    'title' => 'Islandora Usage Stats CSV',
    'description' => 'Configure the Islandora Usage Stats CSV module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_usage_stats_csv_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora/object/%islandora_object/usage_stats_csv'] = array(
    'page callback' => 'islandora_usage_stats_csv_download_csv',
    'page arguments' => array(2),
    // Access control is handled in the callback so we can respond with
    // just a 403 and no HTML markup.
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Admin form definition.
 */
function islandora_usage_stats_csv_admin_settings() {
  module_load_include('inc', 'islandora_usage_stats_csv', 'includes/utilities');
  $form = array();
  $form['islandora_usage_stats_csv_object_views_label'] = array(
    '#type' => 'textfield',
    '#size' => '10',
    '#title' => t('Label to use for object views'),
    '#default_value' => variable_get('islandora_usage_stats_csv_object_views_label', 'Item'),
    '#description' => t("The word describing object views, e.g., Object, Record, Item."),
  );
  $form['islandora_usage_stats_csv_per_ds'] = array(
    '#type' => 'checkbox',
    '#title' => t('Provide datastream-level download statistics'),
    '#default_value' => variable_get('islandora_usage_stats_csv_per_ds', 1),
    '#description' => t("If enabled, each datastream that has been downloaded will have its own row in the CSV file; if not, all downloads usage data will be combined."),
  );
  if (module_exists('islandora_usage_stats_charts')) {
    $other_setting_note = t("This setting should be the same as the 'Omit from downloads stats' setting used by Islandora Usage Stats Charts.");
  }
  else {
    $other_setting_note = '';
  }
  $form['islandora_usage_stats_csv_dsids_to_skip'] = array(
    '#type' => 'textfield',
    '#size' => '100',
    '#title' => t('Omit from datastream reports'),
    '#default_value' => variable_get('islandora_usage_stats_csv_dsids_to_skip', 'RELS-EXT,RELS-INT,TECHMD,MODS,DC'),
    '#description' => t("Comma-separated list of datastream IDs to exclude from usage stats. All other datastreams will be included. If left blank, all datastreams will be included. !other_setting_note", array('!other_setting_note' => $other_setting_note)),
  );
  $form['islandora_usage_stats_csv_cmodels'] = array(
    '#title' => t("Allowed content models"),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $cmodels = islandora_usage_stats_csv_get_cmodels();
  $form['islandora_usage_stats_csv_cmodels']['islandora_usage_stats_csv_allowed_cmodels'] = array(
    '#type' => 'checkboxes',
    '#options' => $cmodels,
    '#default_value' => variable_get('islandora_usage_stats_csv_allowed_cmodels', array()),
    '#description' => t("Block containing link to downloadable CSV file will only show up for objects with the selected content models. Note that this setting is not related to displaying the link in Islandora Usage Stats Charts."),
  );
  return system_settings_form($form);
}

/**
 * Menu item callback.
 *
 * Gets usage data and prepare it for download.
 */
function islandora_usage_stats_csv_download_csv($object) {
  if (!islandora_object_access('download islandora usage stats data', $object)) {
    drupal_add_http_header('Status', '403 Forbidden');
    exit();
  }

  module_load_include('inc', 'islandora_usage_stats_csv', 'includes/utilities');
  $per_ds = variable_get('islandora_usage_stats_csv_per_ds', 1);
  $csv_output = islandora_usage_stats_csv_generate_csv($object, $per_ds);

  drupal_add_http_header('Content-type', 'text/csv');
  drupal_add_http_header('Content-length', strlen($csv_output));
  $pid_for_filename = preg_replace('/:/', '_', $object->id);
  $filename = 'usage_stats_' . $pid_for_filename . '.csv';
  drupal_add_http_header('Content-Disposition', 'attachment; filename="' . $filename . '"');
  print $csv_output;
  drupal_page_footer();
}
